# source 'https://rubygems.org'

# # Declare your gem's dependencies in custom_forms.gemspec.
# # Bundler will treat runtime dependencies like base dependencies, and
# # development dependencies will be added by default to the :development group.

# # Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
# gem 'rails', '4.2.0'
# # Use sqlite3 as the database for Active Record
# # Use SCSS for stylesheets
# gem 'bootstrap-sass', '~> 3.3.4'
# gem 'sass-rails', '~> 5.0'
# # Use Uglifier as compressor for JavaScript assets
# gem 'uglifier', '>= 1.3.0'
# # Use CoffeeScript for .coffee assets and views
# gem 'coffee-rails', '~> 4.1.0'
# # See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'haml-rails'
# # gem 'therubyracer', platforms: :ruby

# # Use jquery as the JavaScript library
# gem 'jquery-rails'
# # Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
# gem 'turbolinks'
# # Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.0'
# # bundle exec rake doc:rails generates the API under doc/api.
# gem 'sdoc', '~> 0.4.0', group: :doc

# # Use ActiveModel has_secure_password
# # gem 'bcrypt', '~> 3.1.7'
# gem 'jquery-datatables-rails', '~> 3.3.0'

# # Use Unicorn as the app server
# # gem 'unicorn'
# # Declare any dependencies that are still in development here instead of in
# # your gemspec. These might include edge Rails or gems from your path or
# # Git. Remember to move these dependencies to your gemspec before releasing
# # your gem to rubygems.org.

# # To use a debugger
# # gem 'byebug', group: [:development, :test]

# gem 'pg'
# gem 'haml-rails'
# gem 'rails', '4.2.0'
