require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe OnCallsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # OnCall. As you add validations to OnCall, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OnCallsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all on_calls as @on_calls" do
      on_call = OnCall.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:on_calls)).to eq([on_call])
    end
  end

  describe "GET #show" do
    it "assigns the requested on_call as @on_call" do
      on_call = OnCall.create! valid_attributes
      get :show, {:id => on_call.to_param}, valid_session
      expect(assigns(:on_call)).to eq(on_call)
    end
  end

  describe "GET #new" do
    it "assigns a new on_call as @on_call" do
      get :new, {}, valid_session
      expect(assigns(:on_call)).to be_a_new(OnCall)
    end
  end

  describe "GET #edit" do
    it "assigns the requested on_call as @on_call" do
      on_call = OnCall.create! valid_attributes
      get :edit, {:id => on_call.to_param}, valid_session
      expect(assigns(:on_call)).to eq(on_call)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new OnCall" do
        expect {
          post :create, {:on_call => valid_attributes}, valid_session
        }.to change(OnCall, :count).by(1)
      end

      it "assigns a newly created on_call as @on_call" do
        post :create, {:on_call => valid_attributes}, valid_session
        expect(assigns(:on_call)).to be_a(OnCall)
        expect(assigns(:on_call)).to be_persisted
      end

      it "redirects to the created on_call" do
        post :create, {:on_call => valid_attributes}, valid_session
        expect(response).to redirect_to(OnCall.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved on_call as @on_call" do
        post :create, {:on_call => invalid_attributes}, valid_session
        expect(assigns(:on_call)).to be_a_new(OnCall)
      end

      it "re-renders the 'new' template" do
        post :create, {:on_call => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested on_call" do
        on_call = OnCall.create! valid_attributes
        put :update, {:id => on_call.to_param, :on_call => new_attributes}, valid_session
        on_call.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested on_call as @on_call" do
        on_call = OnCall.create! valid_attributes
        put :update, {:id => on_call.to_param, :on_call => valid_attributes}, valid_session
        expect(assigns(:on_call)).to eq(on_call)
      end

      it "redirects to the on_call" do
        on_call = OnCall.create! valid_attributes
        put :update, {:id => on_call.to_param, :on_call => valid_attributes}, valid_session
        expect(response).to redirect_to(on_call)
      end
    end

    context "with invalid params" do
      it "assigns the on_call as @on_call" do
        on_call = OnCall.create! valid_attributes
        put :update, {:id => on_call.to_param, :on_call => invalid_attributes}, valid_session
        expect(assigns(:on_call)).to eq(on_call)
      end

      it "re-renders the 'edit' template" do
        on_call = OnCall.create! valid_attributes
        put :update, {:id => on_call.to_param, :on_call => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested on_call" do
      on_call = OnCall.create! valid_attributes
      expect {
        delete :destroy, {:id => on_call.to_param}, valid_session
      }.to change(OnCall, :count).by(-1)
    end

    it "redirects to the on_calls list" do
      on_call = OnCall.create! valid_attributes
      delete :destroy, {:id => on_call.to_param}, valid_session
      expect(response).to redirect_to(on_calls_url)
    end
  end

end
