require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ReimbursementTimesheetsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # ReimbursementTimesheet. As you add validations to ReimbursementTimesheet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ReimbursementTimesheetsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all reimbursement_timesheets as @reimbursement_timesheets" do
      reimbursement_timesheet = ReimbursementTimesheet.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:reimbursement_timesheets)).to eq([reimbursement_timesheet])
    end
  end

  describe "GET #show" do
    it "assigns the requested reimbursement_timesheet as @reimbursement_timesheet" do
      reimbursement_timesheet = ReimbursementTimesheet.create! valid_attributes
      get :show, {:id => reimbursement_timesheet.to_param}, valid_session
      expect(assigns(:reimbursement_timesheet)).to eq(reimbursement_timesheet)
    end
  end

  describe "GET #new" do
    it "assigns a new reimbursement_timesheet as @reimbursement_timesheet" do
      get :new, {}, valid_session
      expect(assigns(:reimbursement_timesheet)).to be_a_new(ReimbursementTimesheet)
    end
  end

  describe "GET #edit" do
    it "assigns the requested reimbursement_timesheet as @reimbursement_timesheet" do
      reimbursement_timesheet = ReimbursementTimesheet.create! valid_attributes
      get :edit, {:id => reimbursement_timesheet.to_param}, valid_session
      expect(assigns(:reimbursement_timesheet)).to eq(reimbursement_timesheet)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new ReimbursementTimesheet" do
        expect {
          post :create, {:reimbursement_timesheet => valid_attributes}, valid_session
        }.to change(ReimbursementTimesheet, :count).by(1)
      end

      it "assigns a newly created reimbursement_timesheet as @reimbursement_timesheet" do
        post :create, {:reimbursement_timesheet => valid_attributes}, valid_session
        expect(assigns(:reimbursement_timesheet)).to be_a(ReimbursementTimesheet)
        expect(assigns(:reimbursement_timesheet)).to be_persisted
      end

      it "redirects to the created reimbursement_timesheet" do
        post :create, {:reimbursement_timesheet => valid_attributes}, valid_session
        expect(response).to redirect_to(ReimbursementTimesheet.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved reimbursement_timesheet as @reimbursement_timesheet" do
        post :create, {:reimbursement_timesheet => invalid_attributes}, valid_session
        expect(assigns(:reimbursement_timesheet)).to be_a_new(ReimbursementTimesheet)
      end

      it "re-renders the 'new' template" do
        post :create, {:reimbursement_timesheet => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested reimbursement_timesheet" do
        reimbursement_timesheet = ReimbursementTimesheet.create! valid_attributes
        put :update, {:id => reimbursement_timesheet.to_param, :reimbursement_timesheet => new_attributes}, valid_session
        reimbursement_timesheet.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested reimbursement_timesheet as @reimbursement_timesheet" do
        reimbursement_timesheet = ReimbursementTimesheet.create! valid_attributes
        put :update, {:id => reimbursement_timesheet.to_param, :reimbursement_timesheet => valid_attributes}, valid_session
        expect(assigns(:reimbursement_timesheet)).to eq(reimbursement_timesheet)
      end

      it "redirects to the reimbursement_timesheet" do
        reimbursement_timesheet = ReimbursementTimesheet.create! valid_attributes
        put :update, {:id => reimbursement_timesheet.to_param, :reimbursement_timesheet => valid_attributes}, valid_session
        expect(response).to redirect_to(reimbursement_timesheet)
      end
    end

    context "with invalid params" do
      it "assigns the reimbursement_timesheet as @reimbursement_timesheet" do
        reimbursement_timesheet = ReimbursementTimesheet.create! valid_attributes
        put :update, {:id => reimbursement_timesheet.to_param, :reimbursement_timesheet => invalid_attributes}, valid_session
        expect(assigns(:reimbursement_timesheet)).to eq(reimbursement_timesheet)
      end

      it "re-renders the 'edit' template" do
        reimbursement_timesheet = ReimbursementTimesheet.create! valid_attributes
        put :update, {:id => reimbursement_timesheet.to_param, :reimbursement_timesheet => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested reimbursement_timesheet" do
      reimbursement_timesheet = ReimbursementTimesheet.create! valid_attributes
      expect {
        delete :destroy, {:id => reimbursement_timesheet.to_param}, valid_session
      }.to change(ReimbursementTimesheet, :count).by(-1)
    end

    it "redirects to the reimbursement_timesheets list" do
      reimbursement_timesheet = ReimbursementTimesheet.create! valid_attributes
      delete :destroy, {:id => reimbursement_timesheet.to_param}, valid_session
      expect(response).to redirect_to(reimbursement_timesheets_url)
    end
  end

end
